language: r
sudo: required
cache:
  - packages
  - github_packages
dist: trusty
r:
    - release
    - devel
before_install:
  - sudo R CMD javareconf
  - Rscript -e 'install.packages("rJava", type = "source")'
r_packages:
    - devtools
    - covr
    - rcmdcheck
r_github_packages:
  - rmsharp/rmsutilityr
script:
  - R CMD build . --compact-vignettes=gs+qpdf
  - R CMD check *tar.gz
after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'
os:
  - osx
warnings_are_errors: false
